# mongo deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1                 # stateful db no replicas   
  selector:
    matchLabels:
      app: mongo              # pods with this label belong to this deployment
  template:                   # config of PODS within deployment
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017 # from mongodb docker hub page
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
---
# mongo internal service 
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP      # default for internal svc
  selector:
    app.kubernetes.io/name: mongo
    # app: mongo
  ports:
    - protocol: TCP
      port: 27017       # same as container port 
      targetPort: 27017 # same as container port 