apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy             # use base 64 + external encryption in practice 
  mongo-password: bW9uZ29wYXNzd29yZA==